[server]
# Server settings for Streamlit Cloud
headless = true
port = 8501

[browser]
# Browser settings
gatherUsageStats = false

[theme]
# App theme
primaryColor = "#4ECDC4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[runner]
# Runner settings
magicEnabled = true

[logger]
# Logging settings
level = "info"